version: "3.9"

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app/home
        target: /home/${USER_NAME}/ws/
    working_dir: /home/${USER_NAME}/ws/api/
    # entrypoint: bash -c "php -S 0.0.0.0:8000 -t public"
    stdin_open: true
    tty: true
