version: "3.9"

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app/home
        target: /home/${USER_NAME}/ws/
    working_dir: /home/${USER_NAME}/ws/api/
    # entrypoint: bash -c "php -S 0.0.0.0:8000 -t public"
    stdin_open: true
    tty: true

  db:
    image: "mariadb:10.3.32-focal"
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0

  flyway:
    image: flyway/flyway
    volumes:
      - type: bind
        source: ./app/home/flyway/sql/
        target: /flyway/sql/
    depends_on:
      - db
    command: -url=jdbc:mysql://db -schemas=carioca -user=root -password=example -connectRetries=60 migrate
